sql_query= """
    CREATE TABLE sign AS 
    SELECT 
	finess,
	COUNT(*) as nb_signa,
	SUM(IIF("Famille principale" = 'Evénements/incidents dans un établissement ou organisme' AND "Ceci est un EIGS" = 'Non',1,0)) as "Nombre d'EI sur la période 36mois",
	SUM(IIF("Ceci est un EIGS" = 'Oui', 1, 0)) as NB_EIGS,
	SUM(IIF("Famille principale" = 'Evénements indésirables/graves associés aux soins' AND "Ceci est un EIGS" = 'Non',1,0)) AS NB_EIAS,
	SUM(IIF("Famille principale" = 'Evénements/incidents dans un établissement ou organisme' AND "Ceci est un EIGS" = 'Non',1,0)) + SUM(IIF("Ceci est un EIGS" = 'Oui', 1, 0)) + SUM(IIF("Famille principale" = 'Evénements indésirables/graves associés aux soins' AND "Ceci est un EIGS" = 'Non',1,0)) AS "Somme EI + EIGS + EIAS sur la période",
	SUM(IIF("Famille principale" = 'Evénements/incidents dans un établissement ou organisme' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Acte de prévention',1,0)) + SUM(IIF("Ceci est un EIGS" = 'Oui' AND "Nature principale" = 'Acte de prévention', 1, 0)) + SUM(IIF("Famille principale" = 'Evénements indésirables/graves associés aux soins' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Acte de prévention',1,0)) AS 'nb EI/EIG : Acte de prévention',
	SUM(IIF("Famille principale" = 'Evénements/incidents dans un établissement ou organisme' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Autre prise en charge',1,0)) + SUM(IIF("Ceci est un EIGS" = 'Oui' AND "Nature principale" = 'Autre prise en charge', 1, 0)) + SUM(IIF("Famille principale" = 'Evénements indésirables/graves associés aux soins' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Autre prise en charge',1,0)) AS 'nb EI/EIG : Autre prise en charge',
	SUM(IIF("Famille principale" = 'Evénements/incidents dans un établissement ou organisme' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Chute',1,0)) + SUM(IIF("Ceci est un EIGS" = 'Oui' AND "Nature principale" = 'Chute', 1, 0)) + SUM(IIF("Famille principale" = 'Evénements indésirables/graves associés aux soins' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Chute',1,0)) AS 'nb EI/EIG : Chute',
	SUM(IIF("Famille principale" = 'Evénements/incidents dans un établissement ou organisme' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Disparition inquiétante et fugues (Hors SDRE/SDJ/SDT)',1,0)) + SUM(IIF("Ceci est un EIGS" = 'Oui' AND "Nature principale" = 'Disparition inquiétante et fugues (Hors SDRE/SDJ/SDT)', 1, 0)) + SUM(IIF("Famille principale" = 'Evénements indésirables/graves associés aux soins' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Disparition inquiétante et fugues (Hors SDRE/SDJ/SDT)',1,0)) AS 'nb EI/EIG : Disparition inquiétante et fugues (Hors SDRE/SDJ/SDT)',
	SUM(IIF("Famille principale" = 'Evénements/incidents dans un établissement ou organisme' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Dispositif médical',1,0)) + SUM(IIF("Ceci est un EIGS" = 'Oui' AND "Nature principale" = 'Dispositif médical', 1, 0)) + SUM(IIF("Famille principale" = 'Evénements indésirables/graves associés aux soins' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Dispositif médical',1,0)) AS 'nb EI/EIG : Dispositif médical',
	SUM(IIF("Famille principale" = 'Evénements/incidents dans un établissement ou organisme' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Fausse route',1,0)) + SUM(IIF("Ceci est un EIGS" = 'Oui' AND "Nature principale" = 'Fausse route', 1, 0)) + SUM(IIF("Famille principale" = 'Evénements indésirables/graves associés aux soins' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Fausse route',1,0)) AS 'nb EI/EIG : Fausse route',
	SUM(IIF("Famille principale" = 'Evénements/incidents dans un établissement ou organisme' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Infection associée aux soins (IAS) hors ES',1,0)) + SUM(IIF("Ceci est un EIGS" = 'Oui' AND "Nature principale" = 'Infection associée aux soins (IAS) hors ES', 1, 0)) + SUM(IIF("Famille principale" = 'Evénements indésirables/graves associés aux soins' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Infection associée aux soins (IAS) hors ES',1,0)) AS 'nb EI/EIG : Infection associée aux soins (IAS) hors ES',
	SUM(IIF("Famille principale" = 'Evénements/incidents dans un établissement ou organisme' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Infection associée aux soins en EMS et ambulatoire (IAS hors ES)',1,0)) + SUM(IIF("Ceci est un EIGS" = 'Oui' AND "Nature principale" = 'Infection associée aux soins en EMS et ambulatoire (IAS hors ES)', 1, 0)) + SUM(IIF("Famille principale" = 'Evénements indésirables/graves associés aux soins' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Infection associée aux soins en EMS et ambulatoire (IAS hors ES)',1,0)) AS 'nb EI/EIG : Infection associée aux soins en EMS et ambulatoire (IAS hors ES)',
	SUM(IIF("Famille principale" = 'Evénements/incidents dans un établissement ou organisme' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Parcours/Coopération interprofessionnelle',1,0)) + SUM(IIF("Ceci est un EIGS" = 'Oui' AND "Nature principale" = 'Parcours/Coopération interprofessionnelle', 1, 0)) + SUM(IIF("Famille principale" = 'Evénements indésirables/graves associés aux soins' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Parcours/Coopération interprofessionnelle',1,0)) AS 'nb EI/EIG : Parcours/Coopération interprofessionnelle',
	SUM(IIF("Famille principale" = 'Evénements/incidents dans un établissement ou organisme' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Prise en charge chirurgicale',1,0)) + SUM(IIF("Ceci est un EIGS" = 'Oui' AND "Nature principale" = 'Prise en charge chirurgicale', 1, 0)) + SUM(IIF("Famille principale" = 'Evénements indésirables/graves associés aux soins' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Prise en charge chirurgicale',1,0)) AS 'nb EI/EIG : Prise en charge chirurgicale',
	SUM(IIF("Famille principale" = 'Evénements/incidents dans un établissement ou organisme' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Prise en charge diagnostique',1,0)) + SUM(IIF("Ceci est un EIGS" = 'Oui' AND "Nature principale" = 'Prise en charge diagnostique', 1, 0)) + SUM(IIF("Famille principale" = 'Evénements indésirables/graves associés aux soins' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Prise en charge diagnostique',1,0)) AS 'nb EI/EIG : Prise en charge diagnostique',
	SUM(IIF("Famille principale" = 'Evénements/incidents dans un établissement ou organisme' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Prise en charge en urgence',1,0)) + SUM(IIF("Ceci est un EIGS" = 'Oui' AND "Nature principale" = 'Prise en charge en urgence', 1, 0)) + SUM(IIF("Famille principale" = 'Evénements indésirables/graves associés aux soins' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Prise en charge en urgence',1,0)) AS 'nb EI/EIG : Prise en charge en urgence',
	SUM(IIF("Famille principale" = 'Evénements/incidents dans un établissement ou organisme' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Prise en charge médicamenteuse',1,0)) + SUM(IIF("Ceci est un EIGS" = 'Oui' AND "Nature principale" = 'Prise en charge médicamenteuse', 1, 0)) + SUM(IIF("Famille principale" = 'Evénements indésirables/graves associés aux soins' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Prise en charge médicamenteuse',1,0)) AS 'nb EI/EIG : Prise en charge médicamenteuse',
	SUM(IIF("Famille principale" = 'Evénements/incidents dans un établissement ou organisme' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Prise en charge des cancers',1,0)) + SUM(IIF("Ceci est un EIGS" = 'Oui' AND "Nature principale" = 'Prise en charge des cancers', 1, 0)) + SUM(IIF("Famille principale" = 'Evénements indésirables/graves associés aux soins' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Prise en charge des cancers',1,0)) AS 'nb EI/EIG : Prise en charge des cancers',
	SUM(IIF("Famille principale" = 'Evénements/incidents dans un établissement ou organisme' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Prise en charge psychiatrique',1,0)) + SUM(IIF("Ceci est un EIGS" = 'Oui' AND "Nature principale" = 'Prise en charge psychiatrique', 1, 0)) + SUM(IIF("Famille principale" = 'Evénements indésirables/graves associés aux soins' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Prise en charge psychiatrique',1,0)) AS 'nb EI/EIG : Prise en charge psychiatrique',
	SUM(IIF("Famille principale" = 'Evénements/incidents dans un établissement ou organisme' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Suicide',1,0)) + SUM(IIF("Ceci est un EIGS" = 'Oui' AND "Nature principale" = 'Suicide', 1, 0)) + SUM(IIF("Famille principale" = 'Evénements indésirables/graves associés aux soins' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Suicide',1,0)) AS 'nb EI/EIG : Suicide',
	SUM(IIF("Famille principale" = 'Evénements/incidents dans un établissement ou organisme' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Tentative de suicide',1,0)) + SUM(IIF("Ceci est un EIGS" = 'Oui' AND "Nature principale" = 'Tentative de suicide', 1, 0)) + SUM(IIF("Famille principale" = 'Evénements indésirables/graves associés aux soins' AND "Ceci est un EIGS" = 'Non' AND "Nature principale" = 'Tentative de suicide',1,0)) AS 'nb EI/EIG : Tentative de suicide'
    FROM
     (SELECT 
		CASE 
			WHEN substring(tb. "Déclarant organisme
N° FINESS" ,-9) == substring(CAST(tb."Survenue du cas en collectivité
N° FINESS"  as text),1,9)
				THEN substring(tb. "Déclarant organisme
N° FINESS" ,-9)
			WHEN tb."Survenue du cas en collectivité
N° FINESS"  IS NULL
				THEN substring(tb. "Déclarant organisme
N° FINESS" ,-9)
			ELSE 
				substring(CAST(tb."Survenue du cas en collectivité
N° FINESS"  as text),1,9)
		END as finess, *
	 FROM table_signalement tb
	 WHERE
	 tb."Réclamation" != 'Oui') as sub_table
    GROUP BY 1"""